import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api } from './api.js'
import type { ProfileResponse } from './api.js'
import { compact } from './Home.js'
import { useI18n } from './i18n.js'

const DAY=86_400_000
function tokens(row:Record<string,string|number>){return Number(row.uncachedInputTokens??0)+Number(row.cacheReadTokens??0)+Number(row.cacheWriteTokens??0)+Number(row.outputTokens??0)}
export function Profile(){const {zh}=useI18n();const locale=zh?'zh-CN':'en-US';const {login=''}=useParams();const [data,setData]=useState<ProfileResponse>();const [error,setError]=useState<string>();useEffect(()=>{void api<ProfileResponse>(`/api/v1/users/${encodeURIComponent(login)}`).then(setData).catch(cause=>setError(cause instanceof Error?cause.message:(zh?'个人主页暂不可用':'Profile unavailable')))},[login,zh]);if(error!==undefined)return <section className="staticPage"><span className="kicker">{zh?'个人主页':'PROFILE'}</span><h1>{error}</h1><Link to="/">{zh?'返回排行榜':'Back to leaderboard'}</Link></section>;if(data===undefined)return <div className="loadingPage">{zh?'正在加载个人主页…':'Loading profile…'}</div>;const periodLabel=(period:string)=>period==='today'?(zh?'今天':'Today'):period==='7d'?(zh?'近 7 天':'7 Days'):period==='30d'?(zh?'近 30 天':'30 Days'):(zh?'全部时间':'All Time');return <div className="pageStack profilePage">
  <div className="profileActions"><Link to="/">← {zh?'返回排行榜':'Back to leaderboard'}</Link><button onClick={()=>void navigator.clipboard.writeText(window.location.href)}>{zh?'分享链接':'Share link'}</button></div>
  <section className="profileHeader"><div><img src={data.identity.avatarUrl} alt=""/><span><h1>{data.identity.displayName}</h1><a href={data.identity.githubUrl}>@{data.identity.githubLogin} ↗</a></span></div><aside><strong>{compact(data.windows.find(item=>item.period==='all')?.totalTokens??0,locale)}</strong><span>{zh?'总 Token':'Total tokens'}</span></aside></section>
  <section className="windowGrid">{data.windows.map(item=><div key={item.period}><span>{periodLabel(item.period)}</span><strong>{compact(item.totalTokens,locale)}</strong><small>{item.rank===null?(zh?'未上榜':'Unranked'):`#${item.rank}`}</small></div>)}</section>
  <section className="profileData"><div className="heatmapCard"><h2>{zh?'Token 使用 · 52 周':'Token usage · 52 weeks'}</h2><Heatmap days={data.days} zh={zh} locale={locale}/></div><div className="modelCard"><h2>{zh?'模型分布':'Model mix'}</h2><ModelMix models={data.models} zh={zh} locale={locale}/></div></section>
  <p className="selfReported">{zh?'用户自报聚合用量 · UTC 日期 · 永不包含提示词和消息。':'Self-reported aggregate usage · UTC days · prompts and messages are never included.'}</p>
 </div>}

function Heatmap({days,zh,locale}:{days:ProfileResponse['days'];zh:boolean;locale:string}){const cells=useMemo(()=>{const map=new Map(days.map(row=>[String(row.day),tokens(row)]));const today=new Date();const end=Date.UTC(today.getUTCFullYear(),today.getUTCMonth(),today.getUTCDate());const start=end-363*DAY;const values=Array.from({length:364},(_,index)=>{const day=new Date(start+index*DAY).toISOString().slice(0,10);return{day,value:map.get(day)??0}});const max=Math.max(...values.map(item=>item.value),1);return values.map(item=>({...item,level:item.value===0?0:Math.max(1,Math.ceil(item.value/max*4))}))},[days]);return <div><div className="heatmap" aria-label={zh?'每日 Token 使用热力图':'Daily token usage heatmap'}>{cells.map(cell=><span key={cell.day} className={`heat level${cell.level}`} title={`${cell.day}: ${cell.value.toLocaleString(locale)} tokens`}/>)}</div><div className="heatLegend"><span>{zh?'少':'Less'}</span>{[0,1,2,3,4].map(level=><i key={level} className={`heat level${level}`}/>)}<span>{zh?'多':'More'}</span></div></div>}
function ModelMix({models,zh,locale}:{models:ProfileResponse['models'];zh:boolean;locale:string}){const max=Math.max(...models.map(tokens),1);return <div className="modelList">{models.length===0?<span>{zh?'还没有模型数据。':'No model data yet.'}</span>:models.map(row=>{const value=tokens(row);return <div key={`${String(row.provider)}/${String(row.model)}`}><p><span>{String(row.model)}</span><small>{compact(value,locale)}</small></p><div><i style={{width:`${String(Math.max(2,value/max*100))}%`}}/></div><small>{String(row.provider)}</small></div>})}</div>}
